### PR TITLE
Dependency update and migration to Swift.Result

### PR DESCRIPTION
**Pull request by gmoraleda**
New PR containing only the dependency update and the migration to the native Swift.Result.

### CODE REVIEW

**Comment by mono0926** [comment]
@gmoraleda 

I expected the changes of #147 + `Package.swift` diff. Why did you limit the change?

**Comment by mono0926** [comment]
Indeed, I have uncomfortable with some of the changes of #147.
I prefer this pull request. I'll merge a little later 👌

**Comment by gmoraleda** [comment]
I decided to keep this PR small and leave the formatting out.

If you are interested, the tool I use in many of my projects is swiftformat: https://github.com/nicklockwood/SwiftFormat
It runs super fast and helps keeping the formatting consistent when different people work together.

**Comment by mono0926** [comment]
Thanks again!

**Pull request merged**
